CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NO NULL,
    name VARCHAR(60) NOT NULL,
    surname VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
